JuliaData/MemPool.jl

src/MemPool.jl
src/datastore.jl
test/runtests.jl

Some changes and apis to allow optimizing resource usage:
- allow switching off central tracking of `who-has-read-what`; to avoid remote calls when this feature is not needed
- cleanup `FileRef`; to clean up intermediate results
- clean up all stored states; allows a process to clean all intermediate stored results in a session

flexibility to allow apps to use optimizations

---

.gitignore
src/MemPool.jl
test/runtests.jl

Adds an IP address field to identify the node/machine where file is located.
Allows linking only a single IP.
minimal changes to fix #3

keep machine IP with FileRef

---

src/MemPool.jl
src/datastore.jl
test/runtests.jl
test/testenv.jl

- always mmap files in "r+" mode, because the caller may potentially want to update the data
- extend coverage to workers

 always mmap files in "r+" mode

---

src/datastore.jl
test/runtests.jl

By default MemPool will use a random worker on a node to fetch a `FileRef`. Optionally `MemPool.enable_random_fref_serve[]` can be set to `false` to have it use a specific worker (the one with lowest worker id) for this role. Useful in cases where it desirable to have a specific process designated for IO tasks.
Also added tests for new methods.

optoin to return random or specific worker for fileref fetch

---

src/datastore.jl
test/runtests.jl

To avoid master and workers being identified as different IPs.
It can lead to all FileRefs being tagged to master.

use what `getipaddr()` returns for `FileRef` affinity

---

src/io.jl

This fixes a `ArgumentError: type does not have a definite number of fields` issue when column types are unions of bitstypes.

check for isbitsunion in fixedlength

---

src/io.jl

This ensures that we are using the fallback serialization for `Vector{Union{Missing,T}}`. Eventually, we should probably optimize this path.
Fixes #21
cc: @joshday

 Handle Union{Missing,T} in fixlength

---

src/MemPool.jl

Fixes a typo that causes some [malfunction](https://github.com/JuliaComputing/MemPool.jl/issues/27).

Fix typo in deserialize

---

src/MemPool.jl

When a network interface is not available, `Sockets.getipaddr()` will throw an error. This will cause MemPool to fail to load when the user does not have internet access (or another kind of network interface assigning an IP address). Here we catch that error and instead just fall back to `Sockets.localhost` to allow MemPool to load in these cases.

Fix init when without network interface

---

Project.toml
src/MemPool.jl
src/datastore.jl
src/lock.jl
test/runtests.jl

Still encounters some `poolunref called before poolref` assertions on large `Dagger.DArray` operations with many workers, but otherwise I haven't gotten any `KeyError`s with this.

Fix DRef borrowing

---

.gitignore
src/MemPool.jl
test/runtests.jl

Not sure if the implementation for Symbol is really what one wants, but it does yeild the exact same result as Base.summarysize.
Benchmarks:
Before:
```julia
julia> @benchmark MemPool.approx_size("aaaa")
BenchmarkTools.Trial: 
memory estimate:  608 bytes
allocs estimate:  7
--------------
minimum time:     350.000 ns (0.00% GC)
median time:      375.701 ns (0.00% GC)
mean time:        511.096 ns (7.43% GC)
maximum time:     15.956 μs (96.76% GC)
--------------
samples:          10000
evals/sample:     214
```
After:
```julia
julia> @benchmark MemPool.approx_size("aaaa")
BenchmarkTools.Trial: 
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     1.200 ns (0.00% GC)
median time:      1.300 ns (0.00% GC)
mean time:        1.559 ns (0.00% GC)
maximum time:     57.100 …
```

Add approx_size for String and Symbol

---

src/datastore.jl

Fixes task switch during finalizer, which started surfacing after fixing these finalizer task switches https://github.com/JuliaLang/julia/pull/41846
Stress testing (running tons of dtable loads/ops in a loop) the active waiting got at most one iteration in the while loop, so even if it has to wait it leaves that state pretty much immediately.
```
error in running finalizer: ErrorException("task switch not allowed from inside gc finalizer")
jl_error at /opt/julia/src/rtutils.c:41
jl_switch at /opt/julia/src/task.c:481
try_yieldto at ./task.jl:754
wait at ./task.jl:824
wait at ./condition.jl:112
lock at ./lock.jl:100
lock at ./condition.jl:73 [inlined]
lock at ./channels.jl:424 [inlined]
put_buffered at ./channels.jl:320
put! at ./channels.jl:316
unknown function (ip: 0x7f82a06574b0) …
```

fix finalizer task switch

---

src/datastore.jl

So I got a hang as discussed on slack and saw that there was a livelock in `poolset` with gc again
Then I noticed all the locks are obtained using a trylock loop, which isn't necessary.
So i changed the default to lock/unlock and only made it loop in the finalizer unref function

Trylock loops only in the finalizer

---

.gitignore
Project.toml
src/MemPool.jl
src/datastore.jl
src/fsinfo.jl
src/lock.jl
src/storage.jl
test/REQUIRE
test/runtests.jl

This PR implements support for "storage devices", which represent memory, disks, and storage manager algorithms that MemPool can leverage to perform automatic data management. We implement an `SimpleRecencyAllocator` device which, when assigned to one or more `DRef`s (via a `poolset` kwarg), will manage migrating refs from memory to disk (or really between any two devices) as memory fills up, and from disk to memory as data is accessed via `poolget`.
The `SimpleRecencyAllocator` isn't intended to be a perfect, all-encompassing storage manager; instead, it's a simple example of how to do memory management in this new scheme. Interested users are encouraged to implement their own storage devices and managers to suit their workload.
This is also intended as a replacement for some of the …

Add automatic swap-to-disk support

---

src/MemPool.jl
src/datastore.jl

Changelog: 
1. adds `DiskCacheConfig` struct to store/parse/validate disk cache config
2. adds `setup_global_device!` to consume the `DiskCacheConfig` 
3. moved some code around to make it functional

Add disk cache config struct & function to set up disk cache after launch easily

---

src/MemPool.jl
src/datastore.jl
src/storage.jl
test/runtests.jl

Prior to this commit, because it was not possible to decide what
specific files are read from/written to, MemPool was only really useful
for automated swap-to-disk setups. In many realistic scenarios, users
have either existing files that they'd like MemPool to access, or they
want MemPool to write their files with specific and predictable names,
to be consumed by other code or future Julia sessions.
This commit provides this functionality in the form of "tags": a tag is
arbitrary data attached to a `DRef` which is associated with a specific
type of root or leaf device; in the case of `SerializationFileDevice`,
it is a `String` which is the filename that should be used to read/write
the file. Tags are the mechanism by which the user can communicate
specific configurations to storage …

storage: Add root and leaf tags

---

src/datastore.jl
src/storage.jl
test/runtests.jl

We didn't properly maintain the size counters, causing the SRA to bail out, thinking it had no space available. Addresses issues reported in https://github.com/JuliaParallel/DTables.jl/issues/60.

SimpleRecencyAllocator: Decr ctrs in delete_from_device

---

src/datastore.jl
src/storage.jl
test/runtests.jl

MemPool's usage of distributed refcounting and GC finalizers causes slightly excessive memory retention, because it takes sometimes some extra time or an extra GC cycle to clean up data that's been `poolset` once all `DRef`s are freed.
This PR adds an optional user-defined "destructor" callback, which is invoked when an object that's been `poolset` becomes no longer referenced by any `DRef` (which can allow eagerly cleaning up associated memory, rather than letting the GC figure it out on its own). This will be used by Dagger to allow cleaning up cached Dagger task results once all user references are deleted, and the scheduler determines that it no longer needs to use that data. This can cause memory usage to be better controlled when Dagger (and MemPool) are tracking large amounts of …

poolset: Add optional destructor function

---

.github/workflows/test.yml
Project.toml
src/MemPool.jl
src/datastore.jl
src/storage.jl

This PR attempts to work around memory usage issues in a similar manner to the Julia GPU packages: when `poolset` is called, if we're running low on memory (according to a configurable threshold), then we do increasingly expensive calls to the GC to try to free up enough memory to avoid an OOM.
An enhancement that we could make is to keep trying to GC until we don't free any memory. To be investigated.
@stevenwhitaker @svilupp this might help with the OOM issues seen with your workloads.
@krynju I'm considering enabling this by default, do you have any objections to that?

poolset: Call GC when free mem is low

---

.github/workflows/test.yml
Project.toml
src/datastore.jl
src/storage.jl
test/runtests.jl

This PR allows DRefs to be migrated from their current worker to another worker, and have future accesses to the DRef be seamlessly redirected to the new owner. Multiple migrations of the same DRef may occur, and a caching layer will ensure that redirects only add overhead on the first access from each worker after a migration has occurred.
Todo:

Add DRef migration support

---

src/storage.jl

This removes about 55 invalidations from `Base._any()`, which is called by `any()` which is called by `sra_migrate!()`. Not sure why `storage_read()` fails to infer by itself, perhaps because it's using atomics?
Before:
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┬───────────────┬─────────────────┐                                                     
│ <file name>:<line number>                                                                                                         │  Function Name   │ Invalidations │ Invalidations % │                                                     
│ …
```

Add a type assertion to remove some invalidations

---

Project.toml
src/MemPool.jl
src/datastore.jl
src/read_write_lock.jl
src/storage.jl

Vendors the `ConcurrentUtils.ReadWriteLock` to work around Windows incompatibility of Try.jl, until that can be forked to a new organization and issues resolved. In this case, `ReadWriteLock` only needs UnsafeAtomics.jl (which has active maintainers), so we depend on that instead.
Should fix https://github.com/JuliaData/MemPool.jl/issues/84. @DrChainsaw can you validate this?

Vendor ReadWriteLock from ConcurrentUtils

---

Project.toml
src/read_write_lock.jl

This should fix nightly, although we might suffer some performance hits until https://github.com/JuliaLang/julia/pull/45122 is merged.

Remove UnsafeAtomics dependency

---

src/datastore.jl

Otherwise it causes really excessive numbers of GC calls on memory constrained systems like laptops and desktops.

Disable memory reservation check by default
